#### 類別變數

##### 例子
    有序:例如衣服尺寸S、M、L、XL
    無序:顏色 紅、藍、綠，性別(男、女)

In [1]:
import seaborn as sns
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OrdinalEncoder

#自訂類別變數
df = pd.DataFrame([['green','M',10.1,'class1'],
                   ['red','L',13.5,'class2'],
                   ['blue','XL',15.3,'class1']])

df.columns=["color","size","price","class-label"]
print(df)


#自訂index
size_mapping ={"XL":3,
               "L":2,
               "M":1}
df["size1"] = df["size"].map(size_mapping)
print(df) 

 #使用scikit-learn
data = [['Male',1],['Female',3],['Female',2]]
encoder = OrdinalEncoder()
print(encoder.fit_transform(data))

   color size  price class-label
0  green    M   10.1      class1
1    red    L   13.5      class2
2   blue   XL   15.3      class1
   color size  price class-label  size1
0  green    M   10.1      class1      1
1    red    L   13.5      class2      2
2   blue   XL   15.3      class1      3
[[1. 0.]
 [0. 2.]
 [0. 1.]]


##### One-hot Encoding
> 多個欄位轉換，用多維陣列來表示
> 優點:轉換很方便、容易觀察
> 缺點:如果有新資料無法將轉換規則存檔，新資料轉換會有問題

In [3]:
df = pd.DataFrame([['green','M',10.1,'class1'],
                   ['red','L',13.5,'class2'],
                   ['blue','XL',15.3,'class1']
                   ])
df.columns = ['color','size','price','classlabel']
pd.get_dummies(df,columns=['color'],prefix='is' ,prefix_sep='_')



size  price classlabel  is_blue  is_green  is_red
0    M   10.1     class1        0         1       0
1    L   13.5     class2        0         0       1
2   XL   15.3     class1        1         0       0

##### 解決無法存檔的問題
> 利用pandas的 from_dummies 轉換

In [ ]:
df2 =pd.get_dummies(df,columns=['color'],prefix='is' ,prefix_sep='_')
pd.from_dummies(df2[['is_blue','is_green','is_red']],sep="_")

In [13]:
from sklearn.preprocessing import OneHotEncoder
import joblib
X= [["Male",1],["Female",3],["Female",2]]
encoder = OneHotEncoder(handle_unknown='ignore')
X_new = encoder.fit_transform(X)
print(X_new.toarray())
encoder.categories_

color_new = encoder.fit_transform(df[['color']])
column_names = encoder.get_feature_names_out(encoder.feature_names_in_)
df_new = pd.DataFrame(color_new.toarray(),columns=column_names)
df.drop(['color'],axis=1,inplace=True)
df2 = pd.concat([df,df_new],axis=1)
joblib.dump(encoder,'color.joblib')




[[0. 1. 1. 0. 0.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 1. 0.]]


KeyError: "None of [Index(['color'], dtype='object')] are in the [columns]"